# Generated by Django 3.1.2 on 2020-10-05 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu', '0002_auto_20201005_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.questions'),
        ),
    ]
