# Generated by Django 3.1.2 on 2020-10-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_livedoubtsession_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='user_course',
        ),
        migrations.AddField(
            model_name='questions',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.course'),
        ),
    ]
