# Generated by Django 3.1.2 on 2020-10-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_auto_20201010_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='ques_img',
            field=models.ImageField(blank=True, null=True, upload_to='Question'),
        ),
    ]
