# Generated by Django 3.1.2 on 2020-10-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_usermethods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMethods',
        ),
    ]
